"""
Markdownフォーマッター
各カテゴリのMarkdownファイルを生成
"""
from datetime import datetime, timezone, timedelta
from typing import Optional, List, Dict, Any
import yaml
import re


class MarkdownFormatter:
    """Markdownフォーマット生成"""

    JST = timezone(timedelta(hours=9))

    def format_entry(
        self,
        entry_type: str,
        content: str,
        metadata: Dict[str, Any]
    ) -> str:
        """
        エントリをMarkdown形式にフォーマット

        Args:
            entry_type: diary, learning, idea, task
            content: メッセージ内容
            metadata: メタデータ（tags, summaryなど）

        Returns:
            Markdown文字列
        """
        now = datetime.now(self.JST)

        # 基本メタデータ
        frontmatter = {
            "type": entry_type,
            "date": now.strftime("%Y-%m-%d"),
            "tags": metadata.get("tags", []),
            "created_at": now.isoformat(),
            "updated_at": now.isoformat(),
            "line_message_id": metadata.get("line_message_id", "")
        }

        # タイプ固有のメタデータを追加
        type_specific = self._get_type_specific_metadata(entry_type, metadata)
        frontmatter.update(type_specific)

        # Markdownを生成
        body = self._format_body(entry_type, content, metadata)

        # YAMLフロントマター + 本文
        yaml_str = yaml.dump(
            frontmatter,
            allow_unicode=True,
            default_flow_style=False,
            sort_keys=False
        )

        return f"""---
{yaml_str.strip()}
---

{body}

---
*Auto-generated by Life Assistant*
"""

    def _get_type_specific_metadata(
        self,
        entry_type: str,
        metadata: Dict[str, Any]
    ) -> Dict[str, Any]:
        """タイプ固有のメタデータを取得"""
        extracted = metadata.get("extracted_data", {})

        type_metadata = {
            "diary": {
                "mood": extracted.get("mood", "neutral")
            },
            "learning": {
                "topic": extracted.get("topic", metadata.get("summary", "")),
                "difficulty": extracted.get("difficulty", "intermediate")
            },
            "idea": {
                "title": metadata.get("title", metadata.get("summary", "")),
                "status": extracted.get("status", "draft"),
                "priority": extracted.get("priority", "medium")
            },
            "task": {
                "title": metadata.get("title", metadata.get("summary", "")),
                "status": "pending",
                "priority": extracted.get("priority", "medium"),
                "due_date": extracted.get("due_date"),
                "completed_at": None
            }
        }

        return type_metadata.get(entry_type, {})

    def _format_body(
        self,
        entry_type: str,
        content: str,
        metadata: Dict[str, Any]
    ) -> str:
        """本文をフォーマット"""
        now = datetime.now(self.JST)
        date_str = now.strftime("%Y年%m月%d日")
        extracted = metadata.get("extracted_data", {})

        if entry_type == "diary":
            return f"""# {date_str}の日記

{content}
"""

        elif entry_type == "learning":
            topic = extracted.get("topic", metadata.get("summary", "学習メモ"))
            key_concepts = extracted.get("key_concepts", [])
            next_steps = extracted.get("next_steps", [])

            body = f"""# {topic}

## 学んだこと

{content}
"""

            if key_concepts:
                body += "\n## キーポイント\n\n"
                for concept in key_concepts:
                    body += f"- {concept}\n"

            if next_steps:
                body += "\n## 次のステップ\n\n"
                for step in next_steps:
                    body += f"- {step}\n"

            return body

        elif entry_type == "idea":
            title = metadata.get("title", metadata.get("summary", "アイデア"))
            action_items = extracted.get("action_items", [])

            body = f"""# {title}

## 概要

{content}
"""

            if action_items:
                body += "\n## 次のアクション\n\n"
                for item in action_items:
                    body += f"- [ ] {item}\n"

            return body

        elif entry_type == "task":
            title = metadata.get("title", metadata.get("summary", "タスク"))
            subtasks = extracted.get("subtasks", [])

            body = f"""# {title}

## 概要

{content}
"""

            if subtasks:
                body += "\n## サブタスク\n\n"
                for subtask in subtasks:
                    body += f"- [ ] {subtask}\n"

            body += f"""
## 進捗ログ

| 日時 | 更新内容 |
|------|---------|
| {now.strftime("%Y-%m-%d %H:%M")} | タスク作成 |
"""

            return body

        return content

    def generate_file_path(
        self,
        entry_type: str,
        title: Optional[str] = None,
        timestamp: Optional[datetime] = None
    ) -> str:
        """
        ファイルパスを生成

        Args:
            entry_type: カテゴリ
            title: タイトル（ファイル名に使用）
            timestamp: タイムスタンプ（指定がなければ現在時刻）

        Returns:
            ファイルパス文字列
        """
        if timestamp is None:
            timestamp = datetime.now(self.JST)

        date_str = timestamp.strftime("%Y-%m-%d")
        year = timestamp.strftime("%Y")
        month = timestamp.strftime("%m")

        if entry_type == "diary":
            # 日記は日付ごとに1ファイル（追記）
            return f"diary/{year}/{month}/{date_str}.md"

        elif entry_type == "learning":
            safe_title = self._sanitize_filename(title or "note")
            return f"learning/{year}/{month}/{date_str}_{safe_title}.md"

        elif entry_type == "idea":
            safe_title = self._sanitize_filename(title or "idea")
            return f"ideas/{year}/{month}/{date_str}_{safe_title}.md"

        elif entry_type == "task":
            safe_title = self._sanitize_filename(title or "task")
            return f"tasks/active/{date_str}_{safe_title}.md"

        return f"misc/{date_str}.md"

    def _sanitize_filename(self, name: str) -> str:
        """ファイル名として安全な文字列に変換"""
        # 特殊文字を除去
        unsafe_chars = ['/', '\\', ':', '*', '?', '"', '<', '>', '|', '\n', '\r', '\t']
        safe_name = name
        for char in unsafe_chars:
            safe_name = safe_name.replace(char, '')

        # 空白をアンダースコアに
        safe_name = re.sub(r'\s+', '_', safe_name)

        # 連続するアンダースコアを1つに
        safe_name = re.sub(r'_+', '_', safe_name)

        # 長すぎる場合は切り詰め
        if len(safe_name) > 50:
            safe_name = safe_name[:50]

        return safe_name.strip('_') or "untitled"

    def generate_entry_id(
        self,
        entry_type: str,
        timestamp: Optional[datetime] = None
    ) -> str:
        """
        エントリIDを生成

        Returns:
            例: "diary_2025-02-11", "learning_2025-02-11_12345"
        """
        if timestamp is None:
            timestamp = datetime.now(self.JST)

        date_str = timestamp.strftime("%Y-%m-%d")
        time_suffix = timestamp.strftime("%H%M%S")

        if entry_type == "diary":
            return f"diary_{date_str}"
        else:
            return f"{entry_type}_{date_str}_{time_suffix}"

    def format_weekly_review(
        self,
        content: str,
        week: int,
        year: int,
        start_date: str,
        end_date: str
    ) -> str:
        """週次レビューをフォーマット"""
        now = datetime.now(self.JST)

        frontmatter = {
            "type": "weekly_review",
            "week": f"{year}-W{week:02d}",
            "date_range": f"{start_date} ~ {end_date}",
            "generated_at": now.isoformat()
        }

        yaml_str = yaml.dump(
            frontmatter,
            allow_unicode=True,
            default_flow_style=False,
            sort_keys=False
        )

        return f"""---
{yaml_str.strip()}
---

# 週次レビュー: {year}年 第{week}週

{content}

---
*Auto-generated by Life Assistant (Claude AI Analysis)*
"""

    def format_monthly_review(
        self,
        content: str,
        month: int,
        year: int
    ) -> str:
        """月次レビューをフォーマット"""
        now = datetime.now(self.JST)

        frontmatter = {
            "type": "monthly_review",
            "month": f"{year}-{month:02d}",
            "generated_at": now.isoformat()
        }

        yaml_str = yaml.dump(
            frontmatter,
            allow_unicode=True,
            default_flow_style=False,
            sort_keys=False
        )

        return f"""---
{yaml_str.strip()}
---

# 月次レビュー: {year}年{month}月

{content}

---
*Auto-generated by Life Assistant (Claude AI Analysis)*
"""
